hex
===

'hex' is yet another hex viewer.  As of now, there are no advantages to it.

Plans
-----
In the future, it should be able to automatically interpret fields within files
using a set of Lua scripts.

Packages
--------
Regular releases are sporadic.  git master should be stable enough.  You can get
a package with the latest development version from Archlinux's AUR, or from
openSUSE Build Service for the rest of mainstream distributions.  Consult the
list of repositories and their respective links at:

https://build.opensuse.org/project/repositories/home:pjanouch:git

Building and Running
--------------------
Build dependencies: CMake, pkg-config, help2man, liberty (included),
                    termo (included) +
Runtime dependencies: ncursesw, libunistring

 $ git clone --recursive https://github.com/pjanouch/hex.git
 $ mkdir hex/build
 $ cd hex/build
 $ cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Debug
 $ make

To install the application, you can do either the usual:

 # make install

Or you can try telling CMake to make a package for you.  For Debian it is:

 $ cpack -G DEB
 # dpkg -i hex-*.deb

Note that for versions of CMake before 2.8.9, you need to prefix `cpack` with
`fakeroot` or file ownership will end up wrong.

Having the program installed, optionally create a configuration file and run it.

Configuration
-------------
Create _~/.config/hex/hex.conf_ with contents like the following:

....
colors = {
	footer     = ""
	highlight  = "bold"
	bar        = "reverse"
	bar_active = "ul"
	even       = ""
	odd        = ""
	selection  = "reverse"
}
....

Terminal caveats
----------------
Terminals are somewhat tricky to get consistent results on, so be aware of the
following:

 - Xterm needs `XTerm*metaSendsEscape: true` for the default bindings to work
 - urxvt's 'vtwheel' plugin sabotages scrolling

Contributing and Support
------------------------
Use this project's GitHub to report any bugs, request features, or submit pull
requests.  If you want to discuss this project, or maybe just hang out with
the developer, feel free to join me at irc://irc.janouch.name, channel #dev.

License
-------
'hex' is written by Přemysl Janouch <p.janouch@gmail.com>.

You may use the software under the terms of the ISC license, the text of which
is included within the package, or, at your option, you may relicense the work
under the MIT or the Modified BSD License, as listed at the following site:

http://www.gnu.org/licenses/license-list.html
